version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"                  # root workspace
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
  # …and one entry per package if you want fine‑grained control…
